Agregar manejo de sesión para el usuario
IIC2513-2021-1/GudReads pull request #10
Opened 2021-05-06 18:25 UTC by valeeeriquelme

Se agregan las funcionalidades de **Iniciar Sesión y Cerrar Sesión** para el usuario. El manejo de sesión permitirá mantener el estado del usuario y la posibilidad de desarrollar atribuciones/funcionalidades restringidas a él (ej. hacer una publicación desde su cuenta, ver información privada, entre otras).

Para implementar el inicio de sesión se definieron las rutas new y create y la vista asociada para permitirle al usuario ingresar sus credenciales. Para el cierre de sesión se creo la ruta destroy. 

Además, con el uso de middlewares se manejó el estado del usuario (currentUser) para poder acceder a este desde las vistas y así definir que información desplegar: opción de iniciar o cerrar sesión, información del usuario loggeado. Los elementos (inputs) asociados al inicio y cierre de sesión se ubicaron en el header de la vista layout.

**vista index**
- Usuario no ha iniciado sesión 
- Se despliega opción de "Iniciar Sesión"
![image](https://user-images.githubusercontent.com/37518300/117346264-86bef400-ae75-11eb-94b2-b7f408959746.png)

**vista session/new**
- Formulario para iniciar sesión
![image](https://user-images.githubusercontent.com/37518300/117346487-cdace980-ae75-11eb-8b87-a128e30abfd9.png)

**vista session/new**
- Usuario no ingresa correctamente sus credenciales
![image](https://user-images.githubusercontent.com/37518300/117347127-ac003200-ae76-11eb-9364-286382d70e64.png)

**vista index**
- Usuario correctamente loggeado
- Se despliega la opción de cerrar sesión ("salir")
- Se muestra el email del usuario loggeado
![image](https://user-images.githubusercontent.com/37518300/117346730-25e3eb80-ae76-11eb-9225-82c95b54f1a0.png)

2021-05-06 21:13 UTC, B-Dominguez requested changes
Hola! Buen trabajo con la cápsula. No revisé en detalle la PR, pero vi el .envrc _trackeado_ por lo que dejé un comentario. También noté que hay errores de _linter_. Algunos de ellos están acumulados de PR's anteriores, pero otros fueron introducidos ahora. Dejo solicitados los cambios.

2021-05-06 21:13 UTC, B-Dominguez commented on .envrc
> +export DB_PASSWORD=gr_password
Este archivo no debería estar _trackeado_. En el proyecto ya se puede usar un `.env` que ya está especificado en el `.gitignore`. Si se usara `.envrc`, habría que agregarlo al `gitignore` para no _trackear_ credenciales o variables de entorno local en general, al repo.

2021-05-06 21:44 UTC, B-Dominguez commented on README.md
> +- contraseña: KMsnQpv4
Este parece ser un usuario aleatorio generado localmente por _faker_. Esto podrá cambiar en cada ejecución de las _seeds_, por lo que para dejar un usuario base de prueba habría que agregarlo manualmente en la _seed_ respectiva.

2021-05-06 21:49 UTC, sivicencio requested changes
En general está bien la implementación 🎉 

Los cambios más relevantes a solucionar serían respecto al archivo `.envrc` y a los seeds de usuarios.

También dejé varias sugerencia de estilos que normalmente son fáciles de solucionar al ejecutar ESLint. Sin embargo, en la cápsula asociada a este PR no estamos aún utilizando esta herramienta, por lo tanto, sería súper bueno si pueden solucionar "a mano" lo indicado.

2021-05-06 21:49 UTC, sivicencio commented on .envrc
> +export DB_PASSWORD=gr_password
Me sumo al comentario de @B-Dominguez. Este archivo no debería estar versionado. Deberían agregarlo al `.gitignore`. Si gustan, pueden agregar un archivo con nombre `.envrc.example` que tenga el contenido de este archivo, para que así otros desarrolladores sepan qué variables de entorno deben setear al correr la aplicación.

2021-05-06 21:49 UTC, sivicencio commented on README.md
> +- email: Jalen83@gmail.com
Este usuario de prueba no lo veo en el archivo de seeds. Si vamos a dejar un usuario de prueba en Heroku, entonces creo que debería estar en las seeds de forma explícita.

2021-05-06 21:49 UTC, sivicencio commented on src/migrations/20210503202812-create-user.js
> +};
Falta línea en blanco al final (el linter suele detectar estos casos).
```suggestion
};

```

2021-05-06 21:49 UTC, sivicencio commented on src/models/user.js
> +};
Falta línea en blanco al final (el linter suele detectar estos casos).

```suggestion
};

```

2021-05-06 21:49 UTC, sivicencio commented on src/routes.js
> +  });
Si bien no es un error de sintaxis, ser coherente con la "indentación" hace el código más fácil de leer. Este conjunto de líneas está un poco más hacia la derecha que el resto.

2021-05-06 21:49 UTC, sivicencio commented on src/routes.js
> +router.use(async(ctx,next)=>{
Aquí dejo una sugerencia de estilos (que nuevamente es algo que identifica el linter, pero siempre es bueno tenerlo en mente):
```suggestion
router.use(async (ctx, next) => {
```

2021-05-06 21:49 UTC, sivicencio commented on src/routes/session.js
> +    const authenticated = user && password === user.password;
Agregaría un pequeño comentario indicando que estamos haciendo una comparación de password en texto plano de forma intencional, pero que es mejor tener el password encriptado. Puede ser en el formato `TODO`:

```javascript
/* TODO: replace plain-text password comparison with encrypted version */
```

2021-05-06 21:49 UTC, sivicencio commented on src/routes/session.js
> +module.exports = router;
Falta línea en blanco al final.
```suggestion
module.exports = router;

```

2021-05-06 21:49 UTC, sivicencio commented on src/seeds/20210503205007-add-users.js
> +const faker = require('faker');
No veo que `faker` esté agregado como dependencia del proyecto 👀 

De todas formas, no creo que agregue mucho valor tener seeds de 100 usuarios, si su password va a ser generado a través de faker, pues ni siquiera podríamos "utilizarlos" para navegar recursos protegidos de la plataforma.

Retomo mi comentario inicial de que tal vez es mejor crear un único usuario de forma explícita, para así saber cómo ingresar después.

2021-05-06 21:49 UTC, sivicencio commented on src/views/layout.html.ejs
> +        else { %>
Una sugerencia para ahorrar algunas líneas de código:

```suggestion
        <% } else { %>
```

2021-05-06 21:49 UTC, sivicencio commented on src/views/session/new.html.ejs
> +   </form>
Una sugerencia de estilos: indentación del tag de cierre y falta línea en blanco al final.
```suggestion
</form>

```

2021-05-06 22:44 UTC, kelseyfranken commented
Añadimos los siguients cambios:
- Se agrega .envrc a .gitignore
- Se agregan sugerencias de estilo
- Se añade comentario en routes/session.js sobre encriptación de contraseñas.
- Se agregar al archivo de seeds usuario base
- Se _trackea_ _faker_ --> `yarn add faker`

2021-05-06 22:50 UTC, sivicencio approved these changes
Lo dejo aprobado, sin embargo, sigue sin estar `faker` en `package.json` (sí está en `yarn.lock`). Por favor agréguenlo antes de hacer merge.

2021-05-07 00:04 UTC, B-Dominguez approved these changes

2021-05-07 00:04 UTC, merged