Feat/endpoint tests
IIC2513-2021-1/GudReads pull request #26
Opened 2021-06-10 01:16 UTC by dasolari

## What?
- Se implementaron los tests a los endpoints de la api.
- Se incluyó la librería `date-fns` para el formateo de fechas.

## Why?
Para la cápsula 23, necesaria para esta entrega.

## How?
Utilizando supertest para testear los endpoints.

2021-06-10 01:18 UTC, dasolari commented
Están los commits de la cápsula anterior 😓

2021-06-10 01:27 UTC, sivicencio commented
> Están los commits de la cápsula anterior 😓

Es porque probablemente sacaste tu branch desde el branch de la cápsula anterior. Si cambias el `base` del PR al branch de la cápsula anterior, te aparecerá sólo el commit que agregaste. Eso servirá para hacerle review, sin embargo, hay que tener cuidado de cambiar el `base` a `main` cuando lo de la cápsula anterior ya esté merged.

2021-06-10 01:32 UTC, dasolari commented
> > Están los commits de la cápsula anterior 😓
> 
> Es porque probablemente sacaste tu branch desde el branch de la cápsula anterior. Si cambias el `base` del PR al branch de la cápsula anterior, te aparecerá sólo el commit que agregaste. Eso servirá para hacerle review, sin embargo, hay que tener cuidado de cambiar el `base` a `main` cuando lo de la cápsula anterior ya esté merged.

Ahí está, lo recordaré.

2021-06-10 20:20 UTC, sivicencio requested changes
Una sugerencia de test faltante y pequeños fixes. En general se ve súper bien 🎉

2021-06-10 20:20 UTC, sivicencio commented on src/routes/api/authors.test.js
> +describe('Author routes', () => {
Pequeña precisión.
```suggestion
describe('Author API routes', () => {
```

2021-06-10 20:20 UTC, sivicencio commented on src/routes/api/authors.test.js
> +      birthDate: format(new Date(1993, 2, 22), 'yyyy-MM-dd'),
👍🏼

2021-06-10 20:20 UTC, sivicencio commented on src/routes/api/authors.test.js
> +      test('unauthorized get request to endpoint', async () => {
Aquí debería ir algo más descriptivo del response, similar al `404`:
```suggestion
      test('responds with 401 status code', async () => {
```

2021-06-10 20:20 UTC, sivicencio commented on src/routes/api/authors.test.js
> +      });
Además de este test (que creo que está bien para verificar específicamente que se le asignó un `id`), deberíamos incluir también uno de snapshot, para tener un test del response body en su totalidad.

(No saldrá en el video de la cápsula, pero no es problema, se puede entender al mirar el código).

2021-06-10 20:20 UTC, sivicencio commented on src/routes/api/authors.test.js
> +      test('post request actually created the the given author', async () => {
```suggestion
      test('post request actually created the given author', async () => {
```

2021-06-10 20:20 UTC, sivicencio commented on src/routes/api/authors.test.js
> +      test('responds with 201 (created) status code', async () => {
```suggestion
      test('responds with 401 status code', async () => {
```

2021-06-10 20:40 UTC, dasolari commented on src/routes/api/authors.test.js
> +describe('Author routes', () => {
👍

2021-06-10 20:43 UTC, dasolari commented on src/routes/api/authors.test.js
> +      test('post request actually created the the given author', async () => {
Ups

2021-06-10 20:44 UTC, dasolari commented on src/routes/api/authors.test.js
> +      test('responds with 201 (created) status code', async () => {
La maldición del `copy/paste` 🙈

2021-06-10 20:49 UTC, dasolari commented on src/routes/api/authors.test.js
> +      });
Perfecto, agregado!

2021-06-11 04:38 UTC, sivicencio approved these changes
Hay algo que me di cuenta recién, y es que se agregaron varios archivos `.DS_Store` (los típicos de macOS). ¿Podrías, por favor, eliminarlos antes de hacer el merge, y agregar una entrada `.DS_Store` al archivo `.gitignore`?

Voy a aprobarlo de todas maneras ✅

2021-06-11 05:00 UTC, dasolari commented
> Hay algo que me di cuenta recién, y es que se agregaron varios archivos `.DS_Store` (los típicos de macOS). ¿Podrías, por favor, eliminarlos antes de hacer el merge, y agregar una entrada `.DS_Store` al archivo `.gitignore`?
> 
> Voy a aprobarlo de todas maneras ✅

Ya los borré, pero creo que falta que @meretamal de el _approve_.

2021-06-11 06:01 UTC, sivicencio commented
> Ya los borré, pero creo que falta que @meretamal de el _approve_ para que me deje hacer merge.

La verdad estamos requiriendo un solo review, así que no debería estar bloqueado por eso. Yo creo que es porque se abrió un PR donde se agregó la acción de correr los tests a la Github Action. Por alguna razón no se corrió aquí.

2021-06-11 15:33 UTC, dasolari commented
Definitivamente no creo que le pueda hacer _merge_. Corrí los _tests_ de nuevo y están pasando, pero aún así dice que falta algo 😢

2021-06-11 15:41 UTC, merged