feat: Add testing to Github Action
IIC2513-2021-1/GudReads pull request #28
Opened 2021-06-11 01:07 UTC by B-Dominguez

## What?
Se agrega testing a la _Github Action_

## Why?
Se quiere validar que una rama pase todos los tests vigentes antes de que pueda ser _mergeada_ a `main`.

## How?
Se actualiza la _action_ ya creada agregando la configuración de la base de datos, para luego agregar el `step` de correr los tests de _Jest_ con `yarn test`.

## Testing? (almost required)
No aplica testing de código, pero se probó el funcionamiento de la action y sí corre los tests correctamente.

## Screenshots (almost required in frontend)
N/A

## Anything Else? (optional)
- En general me parece mejor práctica separar los archivos de las actions con distintos propósitos (test y lint, en este caso), o al menos hacer jobs distintos. Sin embargo, esta _action_ fue creada para usarse en el proyecto del curso, y correr ambos en un mismo _job_ permite optimizar el uso de los minutos de _Github Actions_, que no son ilimitados.

2021-06-11 04:33 UTC, sivicencio requested changes
Algunas posibles mejoras.

2021-06-11 04:33 UTC, sivicencio commented on .github/workflows/iic2513-node.yml
> +        run: yarn test
Esto lo correría con la opción `--silent`. En el check puedes ver que aparece mucho output actualmente (muchos `console.log` de Sequelize)
```suggestion
        run: yarn test --silent
```

2021-06-11 04:33 UTC, sivicencio commented on .github/workflows/iic2513-node.yml
> +          yarn sequelize db:migrate
¿Esto se puede correr con ambiente `test`? Me llamó la atención en el output que aparece lo siguiente:

```
Loaded configuration file "src/config/database.js".
Using environment "development".
Database iic2513template_test created.
```

```
$ /home/runner/work/GudReads/GudReads/node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 12.22.1, CLI: 6.2.0, ORM: 6.3.5]

Loaded configuration file "src/config/database.js".
Using environment "development".
== 20210419231330-create-author: migrating =======
== 20210419231330-create-author: migrated (0.014s)
```
Si es posible correrlo en ambiente `test`, tal vez no sea necesario setear `DB_NAME` como env variable al principio.

2021-06-11 04:33 UTC, sivicencio commented on .github/workflows/iic2513-node.yml
> +
```suggestion

```

2021-06-11 15:48 UTC, meretamal commented on .github/workflows/iic2513-node.yml
> +          yarn sequelize db:migrate
Si se puede, para esto ejecutar:
```bash
NODE_ENV=test yarn sequelize db:create
```

Si es que no me equivoco, los _tests_ llaman a `sequelize.sync()`, por lo que tampoco sería necesario correr las migraciones

2021-06-11 16:05 UTC, sivicencio commented on .github/workflows/iic2513-node.yml
> +          yarn sequelize db:migrate
Súper, deberíamos usar lo de `NODE_ENV`.

Sobre las migraciones, me parece que estás en lo correcto para este proyecto. Sin embargo, lo dejaría igual para poder tomarlo como template para los otros proyectos. No sabemos en estricto rigor cómo manejarán la base de datos, y tal vez correr las migraciones sea buena idea para cubrir el caso en que no utilicen `sequelize.sync()`

2021-06-11 20:20 UTC, B-Dominguez commented
Actualicé los detalles del flag `--silent` y de un salto de línea que sobraba. Sobre cómo setear la db para los comandos de yarn, lo actualicé a  mediante la definición de la variable de entorno `NODE_ENV` al inicio de cada comando como se sugirió, en vez del parche que tenía de definir DB_NAME.

Eso sí, ahora los tests no pasan todos, pero me parece que no es un problema con la _action_, si no con los tests que se agregaron recientemente (o el código que testean, tal vez)

2021-06-12 16:08 UTC, meretamal commented
@B-Dominguez intenta haciendo un _merge_ desde _main_ a esta rama

2021-06-13 16:44 UTC, B-Dominguez commented
Comprobé corriendo localmente los tests en main y fallan, comprobando que el problema iría por ahí. Quizás al probar los tests de la PR #26 se hizo solo en la branch y no con los cambios actualizados de main 

@dasolari @sivicencio tal vez están más familiarizados con el trabajo de esa PR y entender el problema

2021-06-13 19:46 UTC, sivicencio requested changes
@B-Dominguez Dejé un comentario que debiese solucionar el problema. Sin embargo, me di cuenta de un archivo de tests que estaba faltando y lo agregué en el PR https://github.com/IIC2513-2021-1/GudReads/pull/29.

Sería bueno que se le hiciera merge primero a ese PR, luego tú hicieras merge de main nuevamente, y ahí creo que los tests deberían ejecutarse bien.

2021-06-13 19:46 UTC, sivicencio commented on .github/workflows/iic2513-node.yml
> +        run: yarn test --silent
@B-Dominguez Viendo el output de la ejecución de los tests, muchas rutas están respondiendo con `401` cuando no deberían hacerlo. Me di cuenta de que es porque en #26 se utilizan rutas protegidas, que requieren el uso de JWT, y para eso estamos utilizando una env variable llamada `JWT_SECRET`.

La solución simple sería agregar la env variable a este comando, pero tal vez sería bueno explorar una forma más ordenada de definir variables de ambiente, ya que también estamos utilizando `NODE_ENV`. ¿Existirá por ejemplo una forma de definir un archivo `.env.test` aquí mismo y escribir las env variables ahí?

```suggestion
        run: JWT_SECRET=some-secret yarn test --silent
```

2021-06-13 20:04 UTC, sivicencio commented
@B-Dominguez Ya está merged en `main` el PR #29. Así que resolviendo lo de la env variable mencionada en mi último comentario, deberían pasar los tests aquí.

2021-06-13 22:13 UTC, B-Dominguez commented on .github/workflows/iic2513-node.yml
> +        run: yarn test --silent
Genial, esto efectivamente arregló el problema y la action ya pasó.

Sobre cómo definir las variables env, se hace de hecho bajo la llave `jobs.JOB.env` en el `ACTION.yml`. Para `NODE_ENV` me había hecho ruido ponerla ahí siendo que necesitaba solo para los comandos de la db, pero decantándolo mejor, el job por algo se llama `tests`, y considerando además lo de que ya son dos casos de uso de variables de entorno, concuerdo con que es mejor definirlas ahí (ya lo hice en el último _commit_).

2021-06-13 22:51 UTC, sivicencio approved these changes

2021-06-17 13:41 UTC, merged