api post user
IIC2513-2021-1/GudReads pull request #36
Opened 2021-07-04 04:30 UTC by aljara97

## What?
Se crea la ruta `api/users` de tipo POST, en donde crea un usuario según los atributos entregados, se comprueba que no hayan errores de crlf

## Why?
Este endpoint se crea porque era necesario que en la cápsula 33 la aplicación de frontend llamara a la API para implementar un formulario de registro de usuario

## How?
Se reciben datos a partir del body, si se puede crear un modelo de tipo `user`, la aplicación arroja un status 200 y el usuario serializado, de lo contrario un error 400

## Testing? (almost required)
No se realizó testeo

## Screenshots (almost required in frontend)
La aplicación no cambia visualmente

2021-07-04 19:43 UTC, sivicencio approved these changes

2021-07-05 02:48 UTC, sivicencio requested changes
Un pequeño error que surgió luego de ejecutar la Github Action.

2021-07-05 02:48 UTC, sivicencio commented on src/routes/api/index.js
> +router.use('/users', users.routes());
`users` no está definido (logré que se corriera la action y tiró el error).

2021-07-05 03:05 UTC, aljara97 commented on src/routes/api/index.js
> +router.use('/users', users.routes());
Listo, ahora lo definí en `index.js`

2021-07-05 03:06 UTC, sivicencio approved these changes

2021-07-05 03:07 UTC, merged